### ISSUE TITLE
Cooling flowing lava only generates stone after update of minetest

### ISSUE THREAD

**Issue by Columbus240** [CasimirKaPazi/unternull#7]
I updated my minetest-dev build (master branch) and minetest_game.
After that, cooling flowing lava only generates stone and no ores anymore when using unternull.
I was able to reproduce this with a new game of minetest_game with only unternull.
I suspect the cause being some changed API.

**Comment by bell07** [comment]
It seems the issue is due the  change https://github.com/minetest/minetest_game/commit/e523c3a2965afe76b9102b67992e15fafba1594a
Trough the direct call the "original" function reference is stored in ABM and no overriding is possible anymore for the changed default functions. No idea at the time how to solve it unternull-site
EDIT: I reverted the patch in my local mtg and now the ores enabled lava cooling works again
`git revert e523c3a2965afe76b9102b67992e15fafba1594a`

**Comment by CasimirKaPazi** [comment]
Fixed upstream.
